name: pytorch-env

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - cudatoolkit=11.1
  - git
  - matplotlib
  - numba
  - numpy
  - pandas
  - panel
  - pip
  - pip:
    - -r requirements.txt
  - pyarrow
  - python=3.9
  - python-language-server
  - pytorch=1.9
  - pytorch-lightning
  - scikit-learn
  - scipy
  - torchmetrics
  - torchvision

